//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/UnitSelection/UnitSelection.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UnitSelection : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UnitSelection()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UnitSelection"",
    ""maps"": [
        {
            ""name"": ""Selection"",
            ""id"": ""b19c5584-85f2-4cba-b85c-e4e24a4a8b90"",
            ""actions"": [
                {
                    ""name"": ""Click Select"",
                    ""type"": ""Button"",
                    ""id"": ""a6ba99e3-5134-4f7a-8ded-7b38997fb9b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shift Select"",
                    ""type"": ""Button"",
                    ""id"": ""7ebd39ea-837a-4d73-a97e-0c7c6d7120b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drag Select"",
                    ""type"": ""Button"",
                    ""id"": ""bfcd5b73-bd5e-4f3f-9bac-cff64ccadca6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""46c22b11-f29b-4090-8e57-ae8f4c71429d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1601a41-c8dd-48ea-9219-fe4196e0f443"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shift Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9b47c8e-2b36-4dd5-ab32-666807c4ed17"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drag Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Selection
        m_Selection = asset.FindActionMap("Selection", throwIfNotFound: true);
        m_Selection_ClickSelect = m_Selection.FindAction("Click Select", throwIfNotFound: true);
        m_Selection_ShiftSelect = m_Selection.FindAction("Shift Select", throwIfNotFound: true);
        m_Selection_DragSelect = m_Selection.FindAction("Drag Select", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Selection
    private readonly InputActionMap m_Selection;
    private ISelectionActions m_SelectionActionsCallbackInterface;
    private readonly InputAction m_Selection_ClickSelect;
    private readonly InputAction m_Selection_ShiftSelect;
    private readonly InputAction m_Selection_DragSelect;
    public struct SelectionActions
    {
        private @UnitSelection m_Wrapper;
        public SelectionActions(@UnitSelection wrapper) { m_Wrapper = wrapper; }
        public InputAction @ClickSelect => m_Wrapper.m_Selection_ClickSelect;
        public InputAction @ShiftSelect => m_Wrapper.m_Selection_ShiftSelect;
        public InputAction @DragSelect => m_Wrapper.m_Selection_DragSelect;
        public InputActionMap Get() { return m_Wrapper.m_Selection; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SelectionActions set) { return set.Get(); }
        public void SetCallbacks(ISelectionActions instance)
        {
            if (m_Wrapper.m_SelectionActionsCallbackInterface != null)
            {
                @ClickSelect.started -= m_Wrapper.m_SelectionActionsCallbackInterface.OnClickSelect;
                @ClickSelect.performed -= m_Wrapper.m_SelectionActionsCallbackInterface.OnClickSelect;
                @ClickSelect.canceled -= m_Wrapper.m_SelectionActionsCallbackInterface.OnClickSelect;
                @ShiftSelect.started -= m_Wrapper.m_SelectionActionsCallbackInterface.OnShiftSelect;
                @ShiftSelect.performed -= m_Wrapper.m_SelectionActionsCallbackInterface.OnShiftSelect;
                @ShiftSelect.canceled -= m_Wrapper.m_SelectionActionsCallbackInterface.OnShiftSelect;
                @DragSelect.started -= m_Wrapper.m_SelectionActionsCallbackInterface.OnDragSelect;
                @DragSelect.performed -= m_Wrapper.m_SelectionActionsCallbackInterface.OnDragSelect;
                @DragSelect.canceled -= m_Wrapper.m_SelectionActionsCallbackInterface.OnDragSelect;
            }
            m_Wrapper.m_SelectionActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ClickSelect.started += instance.OnClickSelect;
                @ClickSelect.performed += instance.OnClickSelect;
                @ClickSelect.canceled += instance.OnClickSelect;
                @ShiftSelect.started += instance.OnShiftSelect;
                @ShiftSelect.performed += instance.OnShiftSelect;
                @ShiftSelect.canceled += instance.OnShiftSelect;
                @DragSelect.started += instance.OnDragSelect;
                @DragSelect.performed += instance.OnDragSelect;
                @DragSelect.canceled += instance.OnDragSelect;
            }
        }
    }
    public SelectionActions @Selection => new SelectionActions(this);
    public interface ISelectionActions
    {
        void OnClickSelect(InputAction.CallbackContext context);
        void OnShiftSelect(InputAction.CallbackContext context);
        void OnDragSelect(InputAction.CallbackContext context);
    }
}
