//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Locomotion/Locomotion.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Locomotion : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Locomotion()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Locomotion"",
    ""maps"": [
        {
            ""name"": ""Displacement"",
            ""id"": ""a1d4170a-d0f2-4d7f-9eed-4aa870612b07"",
            ""actions"": [
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""fcc24c4c-6cf7-4527-a202-9a7fce1573b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fe81acc9-0965-4b5a-a434-0e6d20459a5b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Displacement
        m_Displacement = asset.FindActionMap("Displacement", throwIfNotFound: true);
        m_Displacement_RightClick = m_Displacement.FindAction("RightClick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Displacement
    private readonly InputActionMap m_Displacement;
    private IDisplacementActions m_DisplacementActionsCallbackInterface;
    private readonly InputAction m_Displacement_RightClick;
    public struct DisplacementActions
    {
        private @Locomotion m_Wrapper;
        public DisplacementActions(@Locomotion wrapper) { m_Wrapper = wrapper; }
        public InputAction @RightClick => m_Wrapper.m_Displacement_RightClick;
        public InputActionMap Get() { return m_Wrapper.m_Displacement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DisplacementActions set) { return set.Get(); }
        public void SetCallbacks(IDisplacementActions instance)
        {
            if (m_Wrapper.m_DisplacementActionsCallbackInterface != null)
            {
                @RightClick.started -= m_Wrapper.m_DisplacementActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_DisplacementActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_DisplacementActionsCallbackInterface.OnRightClick;
            }
            m_Wrapper.m_DisplacementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
            }
        }
    }
    public DisplacementActions @Displacement => new DisplacementActions(this);
    public interface IDisplacementActions
    {
        void OnRightClick(InputAction.CallbackContext context);
    }
}
